version: 0.0
os: linux
files:
  - source: /content/index.php
    destination: /simple-app
hooks:
  ApplicationStart:
    - location: /scripts/start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /scripts/stop.sh
      timeout: 300
      runas: root